#!/usr/bin/bash
for k in {1..100}
do
  echo no noise run number ${k}
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.8 -fa -quiet -data f-ea-ep &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.9 -fa -quiet -data f-ea-ep &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 1.0 -fa -quiet -data f-ea-ep &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.8 -fr -quiet -data f-ea-ep &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.9 -fr -quiet -data f-ea-ep &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 1.0 -fr -quiet -data f-ea-ep 
done
for i in 0.025 0.05 0.075 0.10 0.125 0.15 0.175 0.20
do
  for k in {1..100}
  do
    echo ea=${i} ep=${i} run number ${k}
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.8 -ea ${i} -ep ${i} -fa -quiet -data f-ea-ep &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.9 -ea ${i} -ep ${i} -fa -quiet -data f-ea-ep &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 1.0 -ea ${i} -ep ${i} -fa -quiet -data f-ea-ep &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.8 -ea ${i} -ep ${i} -fr -quiet -data f-ea-ep &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 0.9 -ea ${i} -ep ${i} -fr -quiet -data f-ea-ep &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -q 1.0 -ea ${i} -ep ${i} -fr -quiet -data f-ea-ep 
  done
done





























