#!/usr/bin/bash
for k in {1..100}
do
  echo no noise run number ${k}
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 500 -q 0.8 -is 3 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 1000 -q 0.8 -is 3 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 2500 -q 0.8 -is 3 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 5000 -q 0.8 -is 3 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 500 -q 0.8 -is 5 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 1000 -q 0.8 -is 5 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 2500 -q 0.8 -is 5 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 5000 -q 0.8 -is 5 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 500 -q 0.8 -is 10 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 1000 -q 0.8 -is 10 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 2500 -q 0.8 -is 10 -ajd -quiet -data num-interactions-ajd &
  java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 5000 -q 0.8 -is 10 -ajd -quiet -data num-interactions-ajd
done
for i in 0.10 0.20
do
  for k in {1..100}
  do
    echo ea=${i} ep=${i} run number ${k}
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 500 -q 0.8 -is 3 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 1000 -q 0.8 -is 3 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 2500 -q 0.8 -is 3 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 5000 -q 0.8 -is 3 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 500 -q 0.8 -is 5 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 1000 -q 0.8 -is 5 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 2500 -q 0.8 -is 5 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 5000 -q 0.8 -is 5 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 500 -q 0.8 -is 10 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 1000 -q 0.8 -is 10 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 2500 -q 0.8 -is 10 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd &
    java -classpath .:./bin:./lib/commons-cli-1.5.0/commons-cli-1.5.0.jar Simulation -g 100000 -n 100 -m 5000 -q 0.8 -is 10 -ea ${i} -ep ${i} -ajd -quiet -data num-interactions-ajd
  done
done

